version: 2.1
jobs:
  build:
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            docker build -t $DOCKERHUB_USERNAME/empmedi:latest -f ops/Dockerfile .
      - run:
          name: Push application Docker image
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/empmedi:latest