version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base.2022.09
        username: $DOCKERHUB_USERNAME
        password: $DOCKERHUB_PASSWORD
    steps:
      - setup_remote_docker:
          docker_layer_caching: 1
      - run:
        name: build
        command: docker build -t $DOCKERHUB_USERNAME/empmed:latest
      - run:
        name: push
        command: echo $DOCKERHUB_PASSWORD |docker login -u $DOCKERHUB_USERNAME --password-stidin && docker push $DOCKERHUB_USERNAME/empmed:latest  