version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2022.09
        auth: 
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - name: imgbuild
        command: docker build -f ops/Dockerfile -t $DOCKERHUB_USERNAME/empmed:latest .
      - name: Push
        command: echo $DOCKERHUB_PASSWORD|docker login -u $DOCKERHUB_USERNAME --password-stdin && docker push $DOCKERHUB_USERNAME/empmed:latest