apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.deployment.name}}
spec:
  selector:
    matchLabels:
      app: {{.Values.deployment.name}}
  template:
    metadata:
      labels:
        app: {{.Values.deployment.name}}
    spec:
      containers:
      - name: {{.Values.deployment.name}}
        image: {{.Values.deployment.image}}:{{.Values.deployment.tag}}
        resources:
          limits:
            memory: {{.Values.deployment.resources.memory}}
            cpu: {{.Values.deployment.resources.cpu}}
        ports:
        - containerPort: {{.Values.service.port}}
