name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: docker build -t dexterquazi/ecom --no-cache -f ops/Dockerfile . 
    - name: Login
      run: docker login -u "${{ secrets.USERNAME }}" -p "${{ secrets.PASSWORD }}"
