name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: docker build -t dexterquazi/ecom --no-cache -f ops/Dockerfile . 
    - name: Login
      run: docker login -u "${{ secrets.USERNAME }}" -p "${{ secrets.PASSWORD }}"
    - name: Push
      run: docker push dexterquazi/ecom
    - name: ssh_instance
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_ADDRESS }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: sudo docker run -d --name 404ops -p 80:80 dexterquazi/ecom
